export interface CityData {
  city: string
  state: string
  stateAbbr: string
  slug: string
  metaTitle: string
  metaDescription: string
  bodyParagraph: string
}

export const cities: CityData[] = [
  {
    city: 'New York',
    state: 'New York',
    stateAbbr: 'NY',
    slug: 'new-york-ny',
    metaTitle: 'AI Home Inspection Software in New York, NY | InspectIQ',
    metaDescription: 'New York home inspectors trust InspectIQ to generate professional AI-powered inspection reports fast. InterNACHI standards, branded PDFs, and client share links — built for NYC\'s high-volume market.',
    bodyParagraph: 'New York\'s real estate market moves at a relentless pace — from co-ops in Manhattan to brownstones in Brooklyn and colonials on Long Island. Home inspectors in New York City and the tri-state area handle more inspections per month than almost anywhere in the country, which means report turnaround time directly impacts your income. InspectIQ\'s AI-powered narrative engine lets New York inspectors complete a fully branded, professional PDF report in a fraction of the time it takes with legacy software — so you can take on more jobs without burning out.',
  },
  {
    city: 'Los Angeles',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'los-angeles-ca',
    metaTitle: 'AI Home Inspection Software in Los Angeles, CA | InspectIQ',
    metaDescription: 'Los Angeles home inspectors use InspectIQ to deliver professional AI inspection reports faster. Built for CA\'s complex real estate disclosures, InterNACHI standards, and high-end client expectations.',
    bodyParagraph: 'Los Angeles inspectors face a uniquely demanding environment — hillside properties prone to drainage issues, aging mid-century homes with outdated electrical, and buyers who expect polished, detailed reports that can withstand agent and attorney scrutiny. InspectIQ is built for that standard. Our AI narrative generator produces detailed, professional-grade findings for every room section, helping LA-area inspectors deliver reports that look as premium as the market they serve.',
  },
  {
    city: 'Chicago',
    state: 'Illinois',
    stateAbbr: 'IL',
    slug: 'chicago-il',
    metaTitle: 'AI Home Inspection Software in Chicago, IL | InspectIQ',
    metaDescription: 'Chicago home inspectors rely on InspectIQ for AI-powered inspection reports that meet Illinois disclosure standards. Generate branded PDFs, share with clients instantly, and close more inspections per week.',
    bodyParagraph: 'Chicago\'s housing stock — two-flats, graystones, brick bungalows, and aging Victorians — demands thorough inspections that cover basements, flat roofs, and the freeze-thaw damage that Illinois winters inflict year after year. InspectIQ gives Chicago home inspectors the tools to document every finding with precision, generate AI-written narratives that explain issues in plain language for buyers, and share client-ready PDF reports the same day the inspection wraps.',
  },
  {
    city: 'Houston',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'houston-tx',
    metaTitle: 'AI Home Inspection Software in Houston, TX | InspectIQ',
    metaDescription: 'Houston home inspectors use InspectIQ to generate professional AI inspection reports that meet TREC standards. Faster reports, branded PDFs, and instant client sharing for Texas\'s busiest market.',
    bodyParagraph: 'Houston is one of the fastest-moving real estate markets in the country, with high transaction volume and TREC-regulated inspection requirements that demand thoroughness and professionalism. Humidity, flooding history, and foundation movement are recurring concerns inspectors must document with care. InspectIQ streamlines the reporting process so Houston inspectors can complete more inspections per week while delivering the detailed, readable reports that buyers, agents, and lenders expect in the Texas market.',
  },
  {
    city: 'Phoenix',
    state: 'Arizona',
    stateAbbr: 'AZ',
    slug: 'phoenix-az',
    metaTitle: 'AI Home Inspection Software in Phoenix, AZ | InspectIQ',
    metaDescription: 'Phoenix home inspectors trust InspectIQ for AI-powered inspection reports built for Arizona\'s desert climate. Document HVAC wear, stucco cracks, and roof UV damage with professional branded PDFs.',
    bodyParagraph: 'In Phoenix, the desert climate creates a distinct set of inspection priorities — UV-degraded roofing materials, overworked HVAC systems, stucco cracking from thermal expansion, and pest activity from termites and scorpions. InspectIQ\'s inspection editor is designed around real-world conditions, giving Phoenix inspectors a room-by-room workflow that covers every Arizona-specific concern while the AI narrative engine turns your field notes into professional, client-ready language automatically.',
  },
  {
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    slug: 'philadelphia-pa',
    metaTitle: 'AI Home Inspection Software in Philadelphia, PA | InspectIQ',
    metaDescription: 'Philadelphia home inspectors use InspectIQ to generate AI-powered inspection reports for row homes, twins, and older PA housing stock. Faster turnaround, branded PDFs, and instant client share links.',
    bodyParagraph: 'Philadelphia\'s older housing stock — row homes, twin houses, and pre-war brick structures — demands inspectors who understand the unique challenges of aging construction: knob-and-tube wiring, cast iron drain lines, single-pane windows, and brick pointing deterioration. InspectIQ helps Philly inspectors document these issues efficiently and generate written narratives that clearly explain the implications to buyers who may be purchasing their first older home.',
  },
  {
    city: 'San Antonio',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'san-antonio-tx',
    metaTitle: 'AI Home Inspection Software in San Antonio, TX | InspectIQ',
    metaDescription: 'San Antonio home inspectors use InspectIQ to generate TREC-compliant AI inspection reports fast. Cover foundation movement, HVAC, and plumbing issues with professional branded PDFs and client share links.',
    bodyParagraph: 'San Antonio\'s expansive clay soils are notorious for causing foundation movement, and the region\'s hot summers push HVAC systems hard — making thorough mechanical and structural documentation critical for every inspection. InspectIQ gives San Antonio home inspectors a streamlined workflow to capture and report these findings clearly, with AI-generated narratives that translate technical observations into plain-language explanations buyers can actually understand and act on.',
  },
  {
    city: 'San Diego',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'san-diego-ca',
    metaTitle: 'AI Home Inspection Software in San Diego, CA | InspectIQ',
    metaDescription: 'San Diego home inspectors use InspectIQ for AI-powered reports built for coastal California properties. Cover salt air corrosion, hillside drainage, and aging systems with branded PDFs and instant client links.',
    bodyParagraph: 'San Diego\'s coastal communities present inspectors with salt-air corrosion on exterior metals, hillside properties with drainage challenges, and a mix of mid-century and new construction that requires broad expertise. The competitive Southern California market means buyers expect thorough, professionally presented reports quickly. InspectIQ helps San Diego inspectors meet that expectation — delivering polished, AI-assisted reports with client share links the same evening the inspection is completed.',
  },
  {
    city: 'Dallas',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'dallas-tx',
    metaTitle: 'AI Home Inspection Software in Dallas, TX | InspectIQ',
    metaDescription: 'Dallas home inspectors use InspectIQ for fast, professional AI inspection reports. Meet TREC standards, document foundation and HVAC issues, and share reports with clients instantly via branded PDFs.',
    bodyParagraph: 'Dallas is one of Texas\'s most active real estate markets, with a constant influx of relocating buyers who need clear, trustworthy inspection reports to make confident purchasing decisions in an unfamiliar market. InspectIQ helps Dallas home inspectors build that trust by generating polished, easy-to-read reports that stand out from handwritten or template-based alternatives — complete with AI narratives, photo documentation, and a professional branded PDF delivered the same day.',
  },
  {
    city: 'San Jose',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'san-jose-ca',
    metaTitle: 'AI Home Inspection Software in San Jose, CA | InspectIQ',
    metaDescription: 'San Jose home inspectors use InspectIQ for AI-powered inspection reports built for Silicon Valley\'s demanding buyers. Generate branded PDFs with seismic, drainage, and aging system findings — fast.',
    bodyParagraph: 'Silicon Valley buyers are often among the most analytically rigorous home purchasers in the country — and they expect inspection reports that match their standards. In San Jose\'s high-stakes market, a well-written, professionally formatted report isn\'t optional, it\'s a competitive necessity. InspectIQ helps San Jose inspectors produce detailed, AI-assisted reports that include seismic considerations, drainage concerns, and aging system documentation in the clear, precise language that Bay Area buyers and their attorneys expect.',
  },
  {
    city: 'Austin',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'austin-tx',
    metaTitle: 'AI Home Inspection Software in Austin, TX | InspectIQ',
    metaDescription: 'Austin home inspectors use InspectIQ to generate professional AI inspection reports fast. TREC standards, branded PDFs, client share links — built for Austin\'s high-growth real estate market.',
    bodyParagraph: 'Austin\'s explosive population growth has driven massive new construction alongside a wave of buyers purchasing older central Austin bungalows and 1980s-era homes in the suburbs. This mix requires inspectors who can pivot between evaluating fresh builds and aging systems — and clients who expect fast, professional reports in a competitive market. InspectIQ\'s AI report generation helps Austin inspectors meet that demand, turning field notes into polished PDFs in minutes rather than hours.',
  },
  {
    city: 'Jacksonville',
    state: 'Florida',
    stateAbbr: 'FL',
    slug: 'jacksonville-fl',
    metaTitle: 'AI Home Inspection Software in Jacksonville, FL | InspectIQ',
    metaDescription: 'Jacksonville home inspectors use InspectIQ to generate professional AI inspection reports for Florida homes. Document wind mitigation, moisture, and aging systems with branded PDFs and instant client links.',
    bodyParagraph: 'Jacksonville\'s coastal location and subtropical climate make moisture intrusion, roof integrity, and wind-resistance documentation some of the most critical elements of any inspection. Florida buyers and insurers alike scrutinize these findings closely. InspectIQ helps Jacksonville home inspectors document these conditions with precision and generate professional, client-ready reports that hold up to agent and insurer review — without adding hours to the post-inspection workday.',
  },
  {
    city: 'Fort Worth',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'fort-worth-tx',
    metaTitle: 'AI Home Inspection Software in Fort Worth, TX | InspectIQ',
    metaDescription: 'Fort Worth home inspectors use InspectIQ for AI-powered TREC inspection reports. Cover foundation, roofing, and HVAC findings with branded PDFs and client share links built for the DFW market.',
    bodyParagraph: 'Fort Worth\'s rapidly expanding suburbs have created a booming inspection market, with new construction and resale properties filling inspectors\' calendars year-round. Texas clay soils, intense summer heat, and a constant flow of relocation buyers make thorough documentation essential. InspectIQ helps Fort Worth inspectors work faster without cutting corners — generating AI-assisted, fully branded inspection reports that help buyers understand exactly what they\'re purchasing.',
  },
  {
    city: 'Columbus',
    state: 'Ohio',
    stateAbbr: 'OH',
    slug: 'columbus-oh',
    metaTitle: 'AI Home Inspection Software in Columbus, OH | InspectIQ',
    metaDescription: 'Columbus home inspectors use InspectIQ for fast, professional AI inspection reports. Document aging systems, roofing, and HVAC across Ohio\'s diverse housing stock with branded PDFs and client share links.',
    bodyParagraph: 'Columbus is one of the Midwest\'s fastest-growing cities, with a real estate market that spans everything from historic Victorian-era homes near campus to modern new builds in the surrounding suburbs. Ohio\'s weather swings — freezing winters, humid summers — take a toll on roofing, HVAC, and foundation systems that inspectors need to document thoroughly. InspectIQ gives Columbus home inspectors the tools to capture and communicate these findings professionally, with reports clients can actually understand.',
  },
  {
    city: 'Charlotte',
    state: 'North Carolina',
    stateAbbr: 'NC',
    slug: 'charlotte-nc',
    metaTitle: 'AI Home Inspection Software in Charlotte, NC | InspectIQ',
    metaDescription: 'Charlotte home inspectors use InspectIQ to generate AI-powered inspection reports for NC\'s growing market. Branded PDFs, client share links, and AI narratives — built for the Queen City\'s busy inspectors.',
    bodyParagraph: 'Charlotte is one of the Southeast\'s fastest-growing metros, attracting buyers from across the country who are unfamiliar with the local market and heavily reliant on their inspector\'s findings to make informed decisions. With new construction booming alongside established neighborhoods, Charlotte inspectors encounter the full spectrum of home conditions on a daily basis. InspectIQ helps them communicate those findings in a professional, branded format that builds long-term reputation and referral business.',
  },
  {
    city: 'Indianapolis',
    state: 'Indiana',
    stateAbbr: 'IN',
    slug: 'indianapolis-in',
    metaTitle: 'AI Home Inspection Software in Indianapolis, IN | InspectIQ',
    metaDescription: 'Indianapolis home inspectors use InspectIQ for AI-powered inspection reports. Document roofing, HVAC, and basement moisture across Indiana homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Indianapolis offers one of the Midwest\'s most affordable real estate markets, which drives a high volume of first-time buyers who are entirely dependent on a clear, thorough inspection report to guide their decision. InspectIQ helps Indianapolis home inspectors serve these clients well by generating readable, professional-quality reports with AI-written narratives that explain findings without jargon — turning a technical inspection into a genuinely useful buyer education tool.',
  },
  {
    city: 'San Francisco',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'san-francisco-ca',
    metaTitle: 'AI Home Inspection Software in San Francisco, CA | InspectIQ',
    metaDescription: 'San Francisco home inspectors use InspectIQ for AI inspection reports built for the Bay Area. Document seismic retrofitting needs, aging Victorians, and hillside drainage with branded PDFs and client links.',
    bodyParagraph: 'San Francisco\'s Victorian and Edwardian housing stock is architecturally stunning and structurally complex — requiring inspectors to assess soft-story conditions, cripple wall retrofitting needs, aging electrical panels, and the moisture intrusion common in the city\'s foggy microclimates. Buyers in this market are sophisticated and often transact at multi-million-dollar price points, making a thorough, professionally formatted inspection report essential. InspectIQ helps SF inspectors produce exactly that, faster than any alternative.',
  },
  {
    city: 'Seattle',
    state: 'Washington',
    stateAbbr: 'WA',
    slug: 'seattle-wa',
    metaTitle: 'AI Home Inspection Software in Seattle, WA | InspectIQ',
    metaDescription: 'Seattle home inspectors use InspectIQ for AI-powered inspection reports built for the Pacific Northwest. Document moisture, rot, drainage, and seismic concerns with branded PDFs and instant client share links.',
    bodyParagraph: 'Seattle\'s relentless rainfall makes moisture management the defining concern of nearly every inspection in the Pacific Northwest — from roof drainage and flashing integrity to crawl space vapor barriers and siding deterioration. Buyers in Seattle\'s competitive market expect fast turnaround on thorough reports. InspectIQ helps Seattle inspectors meet that bar, generating detailed AI narratives around moisture findings and other conditions while delivering a polished, client-ready PDF the same day.',
  },
  {
    city: 'Denver',
    state: 'Colorado',
    stateAbbr: 'CO',
    slug: 'denver-co',
    metaTitle: 'AI Home Inspection Software in Denver, CO | InspectIQ',
    metaDescription: 'Denver home inspectors use InspectIQ to generate AI-powered inspection reports for Colorado homes. Cover hail damage, radon, foundation, and HVAC findings with branded PDFs and client share links.',
    bodyParagraph: 'Denver inspectors deal with a distinctive combination of high-altitude UV exposure, frequent hail storms that damage roofing and gutters, expansive soils that stress foundations, and radon levels that require careful documentation. Colorado\'s active real estate market means buyers are often competing on tight timelines and need inspection reports delivered quickly. InspectIQ helps Denver home inspectors work at the speed the market demands while maintaining the thoroughness their reputation depends on.',
  },
  {
    city: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    slug: 'nashville-tn',
    metaTitle: 'AI Home Inspection Software in Nashville, TN | InspectIQ',
    metaDescription: 'Nashville home inspectors use InspectIQ for fast AI inspection reports. Document crawl space moisture, aging systems, and new construction defects across Middle Tennessee with branded PDFs and client links.',
    bodyParagraph: 'Nashville\'s construction boom has brought thousands of new homes to market, but rapid development often means new construction defects that buyers assume they won\'t have to worry about. Meanwhile, older Nashville-area homes face crawl space moisture, aging HVAC systems, and deferred maintenance from years of high occupancy. InspectIQ gives Nashville home inspectors the tools to document all of it efficiently and present findings in a polished, professional format that builds trust with clients and referral agents.',
  },
  {
    city: 'Oklahoma City',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    slug: 'oklahoma-city-ok',
    metaTitle: 'AI Home Inspection Software in Oklahoma City, OK | InspectIQ',
    metaDescription: 'Oklahoma City home inspectors use InspectIQ for AI-powered inspection reports. Document foundation movement, storm damage, and aging systems across Oklahoma homes with branded PDFs and client share links.',
    bodyParagraph: 'Oklahoma City sits in the heart of Tornado Alley, making storm-related damage — roof impact, siding, windows, and structural shifting — a routine part of every inspection. The region\'s expansive soils also cause significant foundation movement that must be carefully documented. InspectIQ helps Oklahoma City inspectors communicate these findings clearly and professionally, with AI-generated narratives that put findings in context for buyers and sellers navigating a fast-moving market.',
  },
  {
    city: 'El Paso',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'el-paso-tx',
    metaTitle: 'AI Home Inspection Software in El Paso, TX | InspectIQ',
    metaDescription: 'El Paso home inspectors use InspectIQ for AI-powered TREC inspection reports. Document desert climate wear, HVAC, and roofing findings with branded PDFs and instant client share links.',
    bodyParagraph: 'El Paso\'s high desert climate — intense sun, low humidity, and dramatic temperature swings between day and night — creates distinct wear patterns that inspectors need to identify and document: UV-cracked caulking, dried-out wood components, flat roof membrane deterioration, and evaporative cooler maintenance issues. InspectIQ gives El Paso home inspectors a streamlined way to capture and communicate these findings in professional, branded reports that meet TREC standards and impress clients.',
  },
  {
    city: 'Washington',
    state: 'District of Columbia',
    stateAbbr: 'DC',
    slug: 'washington-dc',
    metaTitle: 'AI Home Inspection Software in Washington, DC | InspectIQ',
    metaDescription: 'Washington DC home inspectors use InspectIQ for AI inspection reports covering row houses, condos, and historic properties. Branded PDFs, client share links, and AI narratives for the DMV market.',
    bodyParagraph: 'Washington DC\'s housing stock is among the most architecturally diverse in the country — from historic Georgetown row houses and Capitol Hill Victorians to modern condos and Northern Virginia new builds. Inspectors working in the DMV area must be fluent in a wide range of construction types and regulatory considerations. InspectIQ helps DC-area home inspectors document every property type with professional, AI-assisted reports that meet the high standards of a market where buyers are often well-informed and well-represented.',
  },
  {
    city: 'Las Vegas',
    state: 'Nevada',
    stateAbbr: 'NV',
    slug: 'las-vegas-nv',
    metaTitle: 'AI Home Inspection Software in Las Vegas, NV | InspectIQ',
    metaDescription: 'Las Vegas home inspectors use InspectIQ for AI-powered inspection reports built for Nevada\'s desert climate. Document HVAC wear, stucco, pool systems, and roofing with branded PDFs and client links.',
    bodyParagraph: 'Las Vegas inspectors encounter a market flooded with sun-baked stucco homes, pool systems that require careful evaluation, HVAC units working overtime in triple-digit heat, and a high percentage of investor-owned and rental properties that may have seen years of deferred maintenance. InspectIQ helps Las Vegas home inspectors document all of these conditions efficiently, generating professional PDF reports with AI-written narratives that clearly explain findings to buyers — many of whom are purchasing remotely.',
  },
  {
    city: 'Louisville',
    state: 'Kentucky',
    stateAbbr: 'KY',
    slug: 'louisville-ky',
    metaTitle: 'AI Home Inspection Software in Louisville, KY | InspectIQ',
    metaDescription: 'Louisville home inspectors use InspectIQ for AI-powered inspection reports. Document aging bungalows, basement moisture, and HVAC findings across Kentucky homes with branded PDFs and client share links.',
    bodyParagraph: 'Louisville\'s real estate market features a rich mix of early 20th-century bungalows, mid-century ranch homes, and newer suburban developments — each with its own inspection considerations. Basement moisture, aging electrical systems, and HVAC efficiency are recurring documentation priorities for Louisville inspectors. InspectIQ helps them work through a full inspection and generate a complete, professional report efficiently — so they can serve more clients without sacrificing the quality their reputation is built on.',
  },
  {
    city: 'Memphis',
    state: 'Tennessee',
    stateAbbr: 'TN',
    slug: 'memphis-tn',
    metaTitle: 'AI Home Inspection Software in Memphis, TN | InspectIQ',
    metaDescription: 'Memphis home inspectors use InspectIQ for AI-powered inspection reports. Document crawl space conditions, aging systems, and foundation findings across Tennessee homes with branded PDFs and client links.',
    bodyParagraph: 'Memphis has one of the highest concentrations of older housing inventory in the Mid-South, with large numbers of properties built in the 1940s through 1970s that require thorough evaluation of electrical, plumbing, foundation, and crawl space conditions. InspectIQ gives Memphis home inspectors the tools to work through these older properties systematically and generate client-ready reports with AI narratives that explain aging systems and their implications in plain, straightforward language.',
  },
  {
    city: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    slug: 'portland-or',
    metaTitle: 'AI Home Inspection Software in Portland, OR | InspectIQ',
    metaDescription: 'Portland home inspectors use InspectIQ for AI inspection reports built for the Pacific Northwest. Document moisture, rot, seismic, and older system findings across Oregon homes with branded PDFs and client links.',
    bodyParagraph: 'Portland\'s older housing stock — craftsman bungalows, older colonials, and pre-war homes in established neighborhoods — demands inspectors who are fluent in aging construction details: galvanized plumbing, knob-and-tube wiring, wood rot from decades of Pacific Northwest rain, and the deferred maintenance that often accompanies older homes in transitional neighborhoods. InspectIQ helps Portland home inspectors produce detailed, professional reports that communicate these findings clearly and build lasting client relationships.',
  },
  {
    city: 'Baltimore',
    state: 'Maryland',
    stateAbbr: 'MD',
    slug: 'baltimore-md',
    metaTitle: 'AI Home Inspection Software in Baltimore, MD | InspectIQ',
    metaDescription: 'Baltimore home inspectors use InspectIQ for AI inspection reports covering row homes and older MD housing. Document lead paint risk, aging systems, and structural findings with branded PDFs and client links.',
    bodyParagraph: 'Baltimore\'s historic row homes and older urban housing stock present inspectors with a layered set of documentation responsibilities — aging brick construction, potential lead paint presence, galvanized and cast iron plumbing, and basement moisture from the region\'s humid climate. Buyers purchasing in Baltimore often need a thorough, well-written report to negotiate repairs or make informed decisions about renovation scope. InspectIQ helps Baltimore inspectors deliver that level of detail efficiently and professionally.',
  },
  {
    city: 'Milwaukee',
    state: 'Wisconsin',
    stateAbbr: 'WI',
    slug: 'milwaukee-wi',
    metaTitle: 'AI Home Inspection Software in Milwaukee, WI | InspectIQ',
    metaDescription: 'Milwaukee home inspectors use InspectIQ for AI-powered inspection reports. Document freeze-thaw damage, aging systems, and basement conditions across Wisconsin homes with branded PDFs and client share links.',
    bodyParagraph: 'Milwaukee\'s harsh winters subject homes to relentless freeze-thaw cycles that crack masonry, deteriorate roofing, and stress foundation walls year after year. The city\'s large inventory of century-old homes also means inspectors regularly encounter knob-and-tube wiring, cast iron plumbing, and single-pane windows that require careful documentation. InspectIQ helps Milwaukee home inspectors capture all of these conditions and communicate them in polished, professional reports that serve buyers well in a market where older homes are the norm.',
  },
  {
    city: 'Albuquerque',
    state: 'New Mexico',
    stateAbbr: 'NM',
    slug: 'albuquerque-nm',
    metaTitle: 'AI Home Inspection Software in Albuquerque, NM | InspectIQ',
    metaDescription: 'Albuquerque home inspectors use InspectIQ for AI inspection reports built for New Mexico\'s desert climate. Document adobe construction, HVAC, and stucco findings with branded PDFs and instant client links.',
    bodyParagraph: 'Albuquerque\'s unique mix of adobe, stucco, and newer construction gives local inspectors a distinctive inspection environment — one where UV damage, flat roof conditions, and desert-specific drainage concerns appear alongside conventional residential systems. InspectIQ\'s flexible inspection workflow adapts to these property types, helping Albuquerque home inspectors document New Mexico-specific concerns and generate professional, branded reports that stand out in a market where most inspectors still rely on basic templates.',
  },
  {
    city: 'Tucson',
    state: 'Arizona',
    stateAbbr: 'AZ',
    slug: 'tucson-az',
    metaTitle: 'AI Home Inspection Software in Tucson, AZ | InspectIQ',
    metaDescription: 'Tucson home inspectors use InspectIQ for AI-powered inspection reports built for Southern Arizona. Document desert wear, HVAC, flat roofs, and termite risk with branded PDFs and instant client share links.',
    bodyParagraph: 'Tucson\'s Sonoran Desert climate means inspectors deal with UV-degraded roofing, evaporative coolers, termite activity, and the unique drainage challenges of monsoon season on a daily basis. Many Tucson buyers are retirees or remote workers purchasing from out of state, making a clear, detailed inspection report with a shareable client link an especially valuable part of the process. InspectIQ helps Tucson home inspectors deliver exactly that — comprehensive, professional reports without the late-night report-writing grind.',
  },
  {
    city: 'Fresno',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'fresno-ca',
    metaTitle: 'AI Home Inspection Software in Fresno, CA | InspectIQ',
    metaDescription: 'Fresno home inspectors use InspectIQ for AI inspection reports built for Central Valley properties. Document HVAC, aging systems, and heat-related wear with branded PDFs and instant client share links.',
    bodyParagraph: 'Fresno\'s Central Valley climate brings scorching summers that push cooling systems to their limits and cause accelerated wear on roofing materials and exterior finishes. The area\'s mix of agricultural-adjacent properties, older urban homes, and newer suburban builds creates a diverse inspection workload for local inspectors. InspectIQ helps Fresno home inspectors document this variety efficiently, with AI-generated narratives that put every finding in context and a professional PDF ready to share with clients the same evening.',
  },
  {
    city: 'Sacramento',
    state: 'California',
    stateAbbr: 'CA',
    slug: 'sacramento-ca',
    metaTitle: 'AI Home Inspection Software in Sacramento, CA | InspectIQ',
    metaDescription: 'Sacramento home inspectors use InspectIQ for AI-powered CA inspection reports. Document aging systems, roofing, HVAC, and drainage findings with branded PDFs and instant client share links.',
    bodyParagraph: 'Sacramento\'s real estate market has boomed as Bay Area buyers seek more affordable alternatives, driving high inspection volume across a housing stock that ranges from mid-century ranch homes to newer developments in the surrounding suburbs. California\'s disclosure requirements and buyer sophistication demand thorough, professionally presented inspection reports. InspectIQ helps Sacramento home inspectors meet that standard — generating AI-assisted, branded reports that clients appreciate and agents remember.',
  },
  {
    city: 'Mesa',
    state: 'Arizona',
    stateAbbr: 'AZ',
    slug: 'mesa-az',
    metaTitle: 'AI Home Inspection Software in Mesa, AZ | InspectIQ',
    metaDescription: 'Mesa home inspectors use InspectIQ for AI-powered Arizona inspection reports. Document desert climate wear, HVAC, pool systems, and roofing findings with branded PDFs and instant client share links.',
    bodyParagraph: 'Mesa is one of the fastest-growing cities in Arizona, with a real estate market that spans newer master-planned communities and established neighborhoods with homes from the 1970s and 1980s. Pool inspections, HVAC system evaluations, and desert-climate roofing assessments are standard components of nearly every Mesa inspection. InspectIQ helps local inspectors handle the volume efficiently while producing professional-grade reports that reflect the quality of their work and strengthen their local reputation.',
  },
  {
    city: 'Kansas City',
    state: 'Missouri',
    stateAbbr: 'MO',
    slug: 'kansas-city-mo',
    metaTitle: 'AI Home Inspection Software in Kansas City, MO | InspectIQ',
    metaDescription: 'Kansas City home inspectors use InspectIQ for AI-powered inspection reports. Document storm damage, basement moisture, and aging systems across Missouri homes with branded PDFs and client share links.',
    bodyParagraph: 'Kansas City\'s central location makes it a corridor for severe weather — hail, high winds, and tornado-adjacent storm damage that inspectors must document carefully for both buyers and insurance purposes. The metro\'s diverse housing stock, from historic Brookside bungalows to suburban new builds in Johnson County, keeps inspectors encountering a wide range of conditions. InspectIQ helps Kansas City inspectors document all of it clearly and deliver polished reports that buyers and agents trust.',
  },
  {
    city: 'Atlanta',
    state: 'Georgia',
    stateAbbr: 'GA',
    slug: 'atlanta-ga',
    metaTitle: 'AI Home Inspection Software in Atlanta, GA | InspectIQ',
    metaDescription: 'Atlanta home inspectors use InspectIQ for AI-powered inspection reports. Document crawl space moisture, HVAC, and foundation findings across Georgia homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Atlanta\'s humid subtropical climate means crawl space moisture, HVAC efficiency, and pest activity — particularly wood-destroying organisms — are front-and-center documentation priorities for every inspection. The metro\'s rapid growth has also brought a wave of new construction with its own set of quality concerns. InspectIQ helps Atlanta home inspectors document both older Atlanta-area homes and new builds thoroughly, generating professional AI-assisted reports that communicate findings clearly to buyers across all experience levels.',
  },
  {
    city: 'Omaha',
    state: 'Nebraska',
    stateAbbr: 'NE',
    slug: 'omaha-ne',
    metaTitle: 'AI Home Inspection Software in Omaha, NE | InspectIQ',
    metaDescription: 'Omaha home inspectors use InspectIQ for AI-powered inspection reports. Document storm damage, aging systems, and foundation findings across Nebraska homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Omaha\'s real estate market is defined by strong value — affordable homes, steady appreciation, and a steady flow of first-time buyers who are counting on their inspection to understand exactly what they\'re getting. Nebraska\'s severe weather seasons mean hail-damaged roofing and siding are common findings that need clear, accurate documentation. InspectIQ helps Omaha home inspectors build that trust with professional, readable reports that buyers can actually use to make informed decisions.',
  },
  {
    city: 'Colorado Springs',
    state: 'Colorado',
    stateAbbr: 'CO',
    slug: 'colorado-springs-co',
    metaTitle: 'AI Home Inspection Software in Colorado Springs, CO | InspectIQ',
    metaDescription: 'Colorado Springs home inspectors use InspectIQ for AI-powered inspection reports. Document radon, hail damage, HVAC, and foundation findings across Colorado homes with branded PDFs and client links.',
    bodyParagraph: 'Colorado Springs sits at the foot of Pikes Peak with an elevation and weather combination that creates unique inspection priorities: high UV exposure degrading exterior finishes, frequent hail storms battering roofing and gutters, and radon levels that often warrant further testing in El Paso County homes. InspectIQ helps Colorado Springs inspectors document these region-specific concerns clearly and professionally, delivering reports that communicate the mountain-climate risks buyers need to understand before closing.',
  },
  {
    city: 'Raleigh',
    state: 'North Carolina',
    stateAbbr: 'NC',
    slug: 'raleigh-nc',
    metaTitle: 'AI Home Inspection Software in Raleigh, NC | InspectIQ',
    metaDescription: 'Raleigh home inspectors use InspectIQ for AI-powered inspection reports. Document crawl space moisture, HVAC, and new construction findings across NC homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Raleigh\'s Research Triangle market has been one of the fastest-growing in the Southeast for years, drawing a constant wave of relocating tech workers and families who need trustworthy, thorough inspections in a competitive market. New construction quality concerns and crawl space moisture management are consistent findings in the region. InspectIQ helps Raleigh home inspectors serve this high-volume market with professional, AI-assisted reports that build the reputation needed to compete for top agent referrals.',
  },
  {
    city: 'Miami',
    state: 'Florida',
    stateAbbr: 'FL',
    slug: 'miami-fl',
    metaTitle: 'AI Home Inspection Software in Miami, FL | InspectIQ',
    metaDescription: 'Miami home inspectors use InspectIQ for AI-powered inspection reports built for South Florida. Document wind mitigation, moisture intrusion, and aging systems with branded PDFs and instant client share links.',
    bodyParagraph: 'Miami\'s inspection environment is shaped by hurricane preparedness — wind mitigation documentation, impact window and shutter verification, roof covering age and attachment method — alongside the relentless humidity that drives moisture intrusion, mold risk, and HVAC strain in almost every property. International buyers who may be purchasing remotely are a significant portion of the market, making a shareable, polished inspection report an especially important deliverable. InspectIQ helps Miami inspectors produce exactly that, fast.',
  },
  {
    city: 'Cleveland',
    state: 'Ohio',
    stateAbbr: 'OH',
    slug: 'cleveland-oh',
    metaTitle: 'AI Home Inspection Software in Cleveland, OH | InspectIQ',
    metaDescription: 'Cleveland home inspectors use InspectIQ for AI-powered inspection reports. Document aging systems, lake-effect moisture, and foundation findings across Ohio homes with branded PDFs and client share links.',
    bodyParagraph: 'Cleveland\'s older housing stock and Lake Erie proximity create a demanding inspection environment — freeze-thaw foundation stress, lake-effect moisture driving basement and crawl space issues, and large numbers of pre-war homes with aging electrical and plumbing systems that require careful documentation. InspectIQ helps Cleveland home inspectors navigate this workload efficiently, generating professional reports with AI-written narratives that explain complex findings in plain language for buyers at every experience level.',
  },
  {
    city: 'Tulsa',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    slug: 'tulsa-ok',
    metaTitle: 'AI Home Inspection Software in Tulsa, OK | InspectIQ',
    metaDescription: 'Tulsa home inspectors use InspectIQ for AI-powered inspection reports. Document storm damage, foundation movement, and aging systems across Oklahoma homes with branded PDFs and client share links.',
    bodyParagraph: 'Tulsa sits squarely in Tornado Alley, and the documentation of storm-related damage — impact-damaged roofing, wind-shifted structural components, and water intrusion from severe weather — is a routine part of every inspection in the area. Oklahoma\'s expansive clay soils also contribute to foundation movement that must be carefully evaluated and communicated. InspectIQ helps Tulsa home inspectors document these conditions professionally and efficiently, with reports that hold up to agent and buyer scrutiny.',
  },
  {
    city: 'Arlington',
    state: 'Texas',
    stateAbbr: 'TX',
    slug: 'arlington-tx',
    metaTitle: 'AI Home Inspection Software in Arlington, TX | InspectIQ',
    metaDescription: 'Arlington home inspectors use InspectIQ for AI-powered TREC inspection reports. Document foundation, HVAC, and roofing findings across the DFW Metroplex with branded PDFs and instant client share links.',
    bodyParagraph: 'Arlington sits at the center of the DFW Metroplex, serving one of Texas\'s most active real estate markets with buyers from across the country relocating to the area every month. TREC-compliant inspections, clay soil foundation documentation, and high-heat HVAC evaluation are the backbone of every Arlington inspection. InspectIQ helps Arlington home inspectors meet Texas\'s regulatory standards while delivering the polished, professional reports that keep referrals coming.',
  },
  {
    city: 'New Orleans',
    state: 'Louisiana',
    stateAbbr: 'LA',
    slug: 'new-orleans-la',
    metaTitle: 'AI Home Inspection Software in New Orleans, LA | InspectIQ',
    metaDescription: 'New Orleans home inspectors use InspectIQ for AI inspection reports built for Louisiana\'s unique housing. Document moisture, pier foundations, flood history, and aging systems with branded PDFs and client links.',
    bodyParagraph: 'New Orleans presents one of the most distinctive inspection environments in the country — pier-and-beam foundations, older Creole cottages and shotgun houses, pervasive humidity, and the ever-present concern of flood history and moisture damage that follows properties in a below-sea-level city. InspectIQ helps New Orleans home inspectors navigate these unique property characteristics and communicate their findings in professional, client-ready reports that buyers rely on to understand what they\'re purchasing in this one-of-a-kind market.',
  },
  {
    city: 'Wichita',
    state: 'Kansas',
    stateAbbr: 'KS',
    slug: 'wichita-ks',
    metaTitle: 'AI Home Inspection Software in Wichita, KS | InspectIQ',
    metaDescription: 'Wichita home inspectors use InspectIQ for AI-powered inspection reports. Document storm damage, aging systems, and foundation findings across Kansas homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Wichita\'s position in the Great Plains means inspectors routinely document storm damage, hail-impacted roofing, and the foundation stress caused by Kansas\'s expansive prairie soils. The city\'s affordable real estate market drives strong first-time buyer volume, making clear, educational inspection reports especially valuable. InspectIQ helps Wichita home inspectors produce professional, AI-assisted reports that give first-time buyers the clarity they need to make confident purchasing decisions.',
  },
  {
    city: 'Tampa',
    state: 'Florida',
    stateAbbr: 'FL',
    slug: 'tampa-fl',
    metaTitle: 'AI Home Inspection Software in Tampa, FL | InspectIQ',
    metaDescription: 'Tampa home inspectors use InspectIQ for AI-powered inspection reports built for Florida\'s Gulf Coast. Document wind mitigation, moisture, HVAC, and aging systems with branded PDFs and instant client links.',
    bodyParagraph: 'Tampa Bay\'s real estate market has been one of Florida\'s hottest, attracting buyers from across the country to a coastal market where hurricane preparedness documentation — wind mitigation, roof age, impact openings — is as important as any traditional inspection finding. Inspectors in the Tampa area need to move quickly and produce professional reports to keep pace with buyer demand. InspectIQ helps Tampa home inspectors do exactly that, without sacrificing the thoroughness that builds long-term professional credibility.',
  },
  {
    city: 'Minneapolis',
    state: 'Minnesota',
    stateAbbr: 'MN',
    slug: 'minneapolis-mn',
    metaTitle: 'AI Home Inspection Software in Minneapolis, MN | InspectIQ',
    metaDescription: 'Minneapolis home inspectors use InspectIQ for AI-powered inspection reports. Document freeze-thaw damage, ice dams, aging systems, and basement findings across Minnesota homes with branded PDFs and client links.',
    bodyParagraph: 'Minneapolis winters are among the most demanding for residential structures in the country — ice dams, freeze-thaw foundation stress, and heating system strain are standard inspection priorities from October through April. The Twin Cities\' large inventory of late-Victorian and early 20th-century homes adds aging electrical, plumbing, and structural findings to the mix. InspectIQ helps Minneapolis home inspectors document these conditions efficiently and deliver professional reports that clearly communicate Minnesota-specific risks to buyers.',
  },
  {
    city: 'Detroit',
    state: 'Michigan',
    stateAbbr: 'MI',
    slug: 'detroit-mi',
    metaTitle: 'AI Home Inspection Software in Detroit, MI | InspectIQ',
    metaDescription: 'Detroit home inspectors use InspectIQ for AI-powered inspection reports. Document aging systems, basement moisture, and structural findings across Michigan homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Detroit\'s housing market features some of the most affordable urban real estate in the Midwest, attracting investors and first-time buyers who need detailed, honest inspection reports to understand the true condition of older homes that may have sat vacant or been through multiple ownership cycles. InspectIQ helps Detroit home inspectors produce the thorough, professionally formatted reports that this buyer population depends on — with AI-generated narratives that explain complex findings in clear, plain language.',
  },
  {
    city: 'Boston',
    state: 'Massachusetts',
    stateAbbr: 'MA',
    slug: 'boston-ma',
    metaTitle: 'AI Home Inspection Software in Boston, MA | InspectIQ',
    metaDescription: 'Boston home inspectors use InspectIQ for AI inspection reports built for New England\'s older housing. Document aging systems, moisture, and structural findings for condos and single-family homes with branded PDFs.',
    bodyParagraph: 'Boston\'s real estate market is defined by older multi-family properties, triple-deckers, historic single-family homes, and a condo market driven by students, young professionals, and investors. Inspectors working in Greater Boston must be equally comfortable evaluating 100-year-old building envelopes and modern gut renovations. InspectIQ helps Boston home inspectors document the full spectrum of New England construction conditions and deliver polished, professional reports that stand up in one of the most transaction-intensive markets in the Northeast.',
  },
  {
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    slug: 'pittsburgh-pa',
    metaTitle: 'AI Home Inspection Software in Pittsburgh, PA | InspectIQ',
    metaDescription: 'Pittsburgh home inspectors use InspectIQ for AI-powered inspection reports. Document aging systems, hillside drainage, and structural findings across PA homes with branded PDFs and instant client share links.',
    bodyParagraph: 'Pittsburgh\'s hilly terrain creates a unique set of inspection concerns — retaining wall stability, hillside drainage, and the soil movement that affects foundations on sloped lots across the city\'s many distinct neighborhoods. Combined with a large inventory of older brick and frame homes built before modern building codes, Pittsburgh inspections require experienced inspectors and thorough documentation. InspectIQ helps Pittsburgh home inspectors communicate their findings professionally, with AI-assisted reports that buyers and agents can trust.',
  },
]

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug)
}

export function getAllSlugs(): string[] {
  return cities.map((c) => c.slug)
}
