// InterNACHI Standards of Practice — Inspection Templates
// Based on the International Association of Certified Home Inspectors SOP
// https://www.internachi.org/standards

export const INTERNACHI_BADGE = 'InterNACHI Standards of Practice'

export const DEFAULT_ROOMS = [
  {
    name: 'Roofing System',
    standard: 'InterNACHI SOP 2.1',
    items: [
      'Roof covering material & condition',
      'Flashing at roof penetrations',
      'Flashing at chimneys & walls',
      'Ridge, hips & valleys',
      'Gutters & downspouts',
      'Downspout termination & drainage',
      'Soffit & fascia condition',
      'Roof ventilation',
      'Skylights & roof windows',
      'Chimney cap & crown',
      'Chimney masonry & mortar',
      'Antenna & satellite dish attachments',
    ],
  },
  {
    name: 'Exterior',
    standard: 'InterNACHI SOP 2.2',
    items: [
      'Wall cladding & siding',
      'Trim, eaves & fascia',
      'Exterior doors & frames',
      'Window caulking & seals',
      'Grading & drainage slope',
      'Walkways, driveways & patios',
      'Deck or porch structure',
      'Deck railings & guards',
      'Stairway condition & handrail',
      'Vegetation clearance from structure',
      'Fencing & gates',
      'Exterior lighting',
    ],
  },
  {
    name: 'Foundation & Crawlspace',
    standard: 'InterNACHI SOP 2.3',
    items: [
      'Foundation wall material & condition',
      'Evidence of settlement or cracking',
      'Evidence of water intrusion or staining',
      'Crawlspace access & clearance',
      'Crawlspace ventilation',
      'Vapor barrier condition',
      'Subfloor structure & framing',
      'Sump pump (if present)',
      'Insulation in crawlspace',
      'Pest or moisture damage evidence',
    ],
  },
  {
    name: 'Attic & Insulation',
    standard: 'InterNACHI SOP 2.8',
    items: [
      'Attic access condition',
      'Roof framing — rafters & sheathing',
      'Evidence of water leaks or staining',
      'Insulation type & depth (R-value)',
      'Insulation distribution & coverage',
      'Ridge vent & soffit ventilation',
      'Powered attic ventilators',
      'HVAC ducts in attic',
      'Exhaust fans termination (bath/kitchen)',
      'Evidence of pest activity',
      'Fire blocking & draft stopping',
    ],
  },
  {
    name: 'Electrical System',
    standard: 'InterNACHI SOP 2.5',
    items: [
      'Main service panel — amperage',
      'Service panel condition & labeling',
      'Double-tapped breakers',
      'AFCI breaker protection',
      'GFCI protection — kitchen',
      'GFCI protection — bathrooms',
      'GFCI protection — garage & exterior',
      'GFCI protection — crawlspace & basement',
      'Visible wiring type & condition',
      'Aluminum branch circuit wiring',
      'Outlets — tested for proper operation',
      'Three-prong grounding verified',
      'Smoke detector locations & function',
      'Carbon monoxide detectors',
      'Exterior panel & weatherproofing',
    ],
  },
  {
    name: 'Plumbing System',
    standard: 'InterNACHI SOP 2.6',
    items: [
      'Water supply material (copper/PEX/galvanized)',
      'Drain, waste & vent material',
      'Water pressure (40–80 psi target)',
      'Main water shut-off location & condition',
      'Water heater age & condition',
      'Water heater TPR valve & discharge pipe',
      'Water heater flue venting',
      'Evidence of active leaks',
      'Evidence of past leaks or staining',
      'Hose bibs & exterior spigots',
      'Laundry hookups — washer drain & supply',
      'Visible drain line slope',
    ],
  },
  {
    name: 'HVAC — Heating',
    standard: 'InterNACHI SOP 2.4',
    items: [
      'Heating system type & fuel source',
      'Furnace / boiler age & condition',
      'Heat exchanger — visible cracks or damage',
      'Flue venting & connections',
      'Filter condition & access',
      'Thermostat operation',
      'Supply & return air registers',
      'Ductwork condition & insulation',
      'Carbon monoxide concern assessment',
      'System operation — heating confirmed',
    ],
  },
  {
    name: 'HVAC — Cooling',
    standard: 'InterNACHI SOP 2.4',
    items: [
      'Cooling system type',
      'Condenser unit age & condition',
      'Condenser clearance & leveling',
      'Refrigerant line insulation',
      'Evaporator coil — accessible condition',
      'Condensate drain & pan',
      'System operation — cooling confirmed',
      'Temperature differential test',
    ],
  },
  {
    name: 'Kitchen',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Cabinets — hardware & structure',
      'Countertops — condition & seams',
      'Sink — supply & drain operation',
      'Faucet — operation & evidence of leaks',
      'Dishwasher — operation & high-loop drain',
      'Range / cooktop — burner operation',
      'Oven — operation',
      'Range hood / exhaust fan',
      'Microwave (built-in)',
      'Refrigerator (if included)',
      'Garbage disposal',
      'GFCI outlets at countertop',
      'Flooring condition',
      'Ceiling & walls condition',
    ],
  },
  {
    name: 'Primary Bathroom',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Toilet — flush & fill operation',
      'Toilet — secure to floor, no rocking',
      'Sink — supply & drain operation',
      'Vanity & cabinet condition',
      'Shower — water operation & pressure',
      'Shower — caulking & grout condition',
      'Shower door / curtain rod',
      'Bathtub — drain & overflow',
      'Tub surround — caulking & tile',
      'Exhaust fan — operation & termination',
      'GFCI outlet',
      'Flooring — soft spots or damage',
      'Ceiling & walls — moisture evidence',
    ],
  },
  {
    name: 'Additional Bathrooms',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Toilet — flush & fill operation',
      'Sink & faucet condition',
      'Shower / tub condition',
      'Caulking & grout',
      'Exhaust fan',
      'GFCI outlet',
      'Flooring condition',
      'Evidence of water damage',
    ],
  },
  {
    name: 'Interior — Living Areas',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Ceilings — cracks, stains, damage',
      'Walls — cracks, damage, moisture',
      'Flooring — type & condition',
      'Interior doors — operation & hardware',
      'Windows — operation & sash condition',
      'Window seals — fogging or failure',
      'Stairways — treads, risers, handrail',
      'Fireplace — damper, firebox, hearth',
      'Fireplace — visible flue condition',
      'Outlets & switches — tested',
      'Smoke detector coverage',
    ],
  },
  {
    name: 'Bedrooms',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Ceiling condition',
      'Wall condition',
      'Flooring condition',
      'Windows — egress requirement met',
      'Window operation & locks',
      'Closet structure & door',
      'Outlets & switches',
      'Smoke detector (required per room)',
      'HVAC supply register',
    ],
  },
  {
    name: 'Garage',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Garage door — manual operation',
      'Garage door opener operation',
      'Auto-reverse safety feature',
      'Photo-eye sensors',
      'Fire-rated door to living space',
      'Fire-rated door — self-closing',
      'Garage floor — cracks & drainage',
      'Ceiling & wall framing',
      'Electrical — outlets & lighting',
      'Ventilation',
      'Vehicle door clearance',
    ],
  },
  {
    name: 'Laundry Room',
    standard: 'InterNACHI SOP 2.9',
    items: [
      'Washer connection — hot & cold supply',
      'Washer drain standpipe',
      'Dryer — 240V outlet or gas connection',
      'Dryer exhaust duct — rigid metal preferred',
      'Dryer exhaust exterior termination',
      'Exhaust duct length & restrictions',
      'Flooring — water damage',
      'Utility sink (if present)',
    ],
  },
]

export type RoomTemplate = typeof DEFAULT_ROOMS[number]
