'use client'

import dynamic from 'next/dynamic'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Download, Loader2, ChevronRight, CheckCircle2 } from 'lucide-react'
import PublicNav from '@/components/layout/PublicNav'
import { useState, useMemo, Suspense } from 'react'
import { pdf } from '@react-pdf/renderer'
import PDFReport from '@/components/report/PDFReport'

const PDFViewer = dynamic(() => import('@react-pdf/renderer').then((m) => m.PDFViewer), {
  ssr: false,
  loading: () => (
    <div className="h-[800px] flex flex-col items-center justify-center bg-slate-50 rounded-xl border border-slate-200">
      <Loader2 className="h-8 w-8 animate-spin text-blue-500 mb-3" />
      <p className="text-slate-500 text-sm">Rendering sample report…</p>
    </div>
  ),
})

// ─── Ohio / InterNACHI sample data ──────────────────────────────────────────
// This is a genuine report generated by InspectIQ — fictional client, real output.

const OH_PROFILE = {
  id: 'demo',
  email: 'james@summitinspects.com',
  fullName: 'James Whitfield',
  companyName: 'Summit Home Inspections',
  licenseNumber: 'HI-OH-4821',
  phone: '(614) 555-0192',
  logoUrl: null,
  signatureUrl: null,
  subscriptionStatus: 'active',
  stripeCustomerId: null,
  stripeSubscriptionId: null,
  trialEndsAt: null,
  createdAt: null,
}

const OH_INSPECTION = {
  id: 'demo',
  propertyAddress: '2847 Oakwood Drive, Columbus, OH 43214',
  clientName: 'Robert & Lisa Harmon',
  clientEmail: 'harmon@email.com',
  inspectionDate: '2025-03-12',
}

const OH_ROOMS = [
  {
    id: 'r1', name: 'Roof System', orderIndex: 0,
    narrative: 'The roof system was inspected from ground level and from accessible eave edges. Asphalt shingle roofing is in overall satisfactory condition with an estimated 5–7 years of remaining service life under normal weather conditions. Gutters and downspouts are functional but contain seasonal debris accumulation that should be cleared before the rainy season to prevent overflow and fascia damage. Step flashing at the chimney base is showing early-stage separation from the brick mortar — this should be monitored and resealed within the next 12 months to prevent water intrusion at that penetration point.',
    items: [
      { id: 'i1', name: 'Asphalt Shingle Roofing', condition: 'good', notes: 'Estimated 5–7 years remaining service life. No missing or visibly damaged shingles observed.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i2', name: 'Gutters & Downspouts', condition: 'fair', notes: 'Debris accumulation in gutters. Clean before rainy season to prevent overflow.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i3', name: 'Chimney Flashing', condition: 'fair', notes: 'Step flashing showing early separation at chimney base. Reseal within 12 months.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i4', name: 'Chimney Structure', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 3 },
      { id: 'i5', name: 'Roof Penetrations & Vents', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 4 },
    ],
  },
  {
    id: 'r2', name: 'Attic & Insulation', orderIndex: 1,
    narrative: 'The attic was accessed via the pull-down stairs in the hallway and inspected with a flashlight. Blown fiberglass insulation is present at approximately R-38, meeting current Ohio energy code requirements. Roof framing is structurally sound with no visible evidence of prior water intrusion, pest activity, or abnormal stress. Ventilation via ridge vent and soffit is functioning as designed. No action required at this time.',
    items: [
      { id: 'i6', name: 'Insulation — Blown Fiberglass', condition: 'good', notes: 'Approximately R-38. Meets current energy code requirements.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i7', name: 'Ridge & Soffit Ventilation', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i8', name: 'Roof Framing', condition: 'good', notes: 'No visible signs of water damage, pest activity, or structural compromise.', aiNarrative: null, photos: '[]', orderIndex: 2 },
    ],
  },
  {
    id: 'r3', name: 'Exterior & Foundation', orderIndex: 2,
    narrative: 'The exterior was inspected from all four elevations. Vinyl siding is in satisfactory condition with no significant damage or areas of moisture intrusion. Minor efflorescence is present on the north foundation wall, which is indicative of past moisture migration through the masonry — this should be monitored seasonally and investigated further if active dampness develops. A critical grading deficiency was identified on the east side of the property: the ground slopes toward the foundation, which channels surface water directly against the structure. This should be corrected by re-grading that section to achieve a minimum 6-inch drop over the first 10 feet away from the foundation.',
    items: [
      { id: 'i9', name: 'Vinyl Siding', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i10', name: 'Foundation Walls', condition: 'fair', notes: 'Minor efflorescence on north wall. Monitor for active moisture intrusion seasonally.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i11', name: 'Site Grading — East Side', condition: 'poor', notes: 'Negative grading on east elevation directs surface water toward foundation. Regrade to achieve positive drainage away from structure.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i12', name: 'Driveway & Walkways', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 3 },
      { id: 'i13', name: 'Doors & Trim', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 4 },
    ],
  },
  {
    id: 'r4', name: 'Kitchen', orderIndex: 3,
    narrative: 'The kitchen is in good overall condition. Cabinets and countertops show typical wear consistent with the age of the home. All included appliances were tested and operated within normal parameters. GFCI protection is present at all countertop outlets as required. A slow drain at the kitchen sink was noted — this is consistent with grease and debris buildup and should be cleared prior to closing to confirm the drain line is functioning properly.',
    items: [
      { id: 'i14', name: 'Cabinets & Countertops', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i15', name: 'Range / Oven', condition: 'good', notes: 'All burners and oven element functional.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i16', name: 'Dishwasher', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i17', name: 'Kitchen Sink & Drain', condition: 'fair', notes: 'Slow drain at kitchen sink. Clear drain line before closing.', aiNarrative: null, photos: '[]', orderIndex: 3 },
      { id: 'i18', name: 'GFCI Outlets', condition: 'good', notes: 'All countertop outlets GFCI-protected and tested functional.', aiNarrative: null, photos: '[]', orderIndex: 4 },
    ],
  },
  {
    id: 'r5', name: 'Electrical System', orderIndex: 4,
    narrative: 'The electrical system is served by a 200-amp service panel located in the utility room. The panel is in satisfactory condition with all breakers properly labeled and no evidence of double-tapping, scorching, or improper wiring observed. All accessible outlets were tested. Two life-safety deficiencies were identified: smoke detectors are absent from the second-floor hallway and master bedroom — these must be installed per NFPA 72 requirements; and no carbon monoxide detector is present within 15 feet of sleeping areas — installation is required per Ohio statute. These items should be corrected immediately.',
    items: [
      { id: 'i19', name: '200-Amp Service Panel', condition: 'good', notes: 'All breakers labeled. No double-tapping or scorching observed.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i20', name: 'Outlets & Switches', condition: 'good', notes: 'All accessible outlets tested functional.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i21', name: 'Smoke Detectors — 2nd Floor', condition: 'poor', notes: 'Smoke detectors absent from 2nd floor hallway and master bedroom. Install per NFPA 72.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i22', name: 'Carbon Monoxide Detector', condition: 'fair', notes: 'No CO detector within 15 feet of sleeping areas. Install per Ohio statute.', aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
  {
    id: 'r6', name: 'HVAC System', orderIndex: 5,
    narrative: 'The heating and cooling systems are in good working condition. The gas forced-air furnace (Carrier, 2019) was tested and is operating within normal parameters. The heat exchanger was visually inspected and shows no visible cracks or corrosion. The central air conditioning unit (Lennox, 2021) is cooling to the expected temperature differential. Ductwork throughout the home is intact with no visible leaks at accessible connections. The air filter was found to be heavily restricted and should be replaced immediately — a monthly replacement schedule is strongly recommended to maintain equipment efficiency and indoor air quality.',
    items: [
      { id: 'i23', name: 'Gas Furnace (Carrier, 2019)', condition: 'good', notes: 'Tested operational. Heat exchanger shows no visible cracks.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i24', name: 'Central A/C (Lennox, 2021)', condition: 'good', notes: 'Cooling to expected differential. Unit in satisfactory condition.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i25', name: 'Ductwork', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i26', name: 'Air Filter', condition: 'fair', notes: 'Filter heavily restricted. Replace immediately and establish monthly replacement schedule.', aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
  {
    id: 'r7', name: 'Plumbing', orderIndex: 6,
    narrative: 'The plumbing system is in satisfactory overall condition. Water supply pressure was measured at 68 PSI, within the normal range of 40–80 PSI. The gas water heater (Rheem, 2020) is functioning properly with the temperature-pressure relief valve present and accessible. All visible supply and drain lines were inspected with no active leaks, corrosion, or improper connections observed. No action required at this time.',
    items: [
      { id: 'i27', name: 'Water Heater (Rheem, 2020)', condition: 'good', notes: 'TPR valve present and accessible. Operating normally.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i28', name: 'Water Supply Pressure', condition: 'good', notes: 'Measured at 68 PSI — within normal range (40–80 PSI).', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i29', name: 'Supply Lines', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i30', name: 'Waste & Drain Lines', condition: 'good', notes: 'No active leaks or improper connections at accessible areas.', aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
  {
    id: 'r8', name: 'Bathrooms', orderIndex: 7,
    narrative: 'The master bathroom and secondary bathroom were both inspected. Toilets are secure and functional. Tub surrounds show grout deterioration and discoloration consistent with age — re-grouting is recommended to prevent water intrusion behind the tile. A critical deficiency was identified in the secondary bathroom: the exhaust fan is non-functional, and visible moisture accumulation and staining on the ceiling confirm prolonged inadequate ventilation. The fan should be repaired or replaced to bring the bathroom into compliance and prevent ongoing moisture damage to the ceiling assembly.',
    items: [
      { id: 'i31', name: 'Toilets', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'i32', name: 'Tub/Shower Grout & Caulk', condition: 'fair', notes: 'Grout discoloration and early deterioration at tub surround. Re-grout recommended.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'i33', name: 'Exhaust Fan — Secondary Bath', condition: 'poor', notes: 'Exhaust fan non-functional. Moisture staining on ceiling. Repair or replace fan.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'i34', name: 'GFCI Outlets', condition: 'good', notes: null, aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
]

// ─── Texas / TREC 7-6 sample data ──────────────────────────────────────────

const TX_PROFILE = {
  id: 'demo-tx',
  email: 'miguel@lonestarhomeinspections.com',
  fullName: 'Miguel Reyes',
  companyName: 'Lone Star Home Inspections',
  licenseNumber: 'TREC-12345',
  phone: '(713) 555-0847',
  logoUrl: null,
  signatureUrl: null,
  subscriptionStatus: 'active',
  stripeCustomerId: null,
  stripeSubscriptionId: null,
  trialEndsAt: null,
  createdAt: null,
}

const TX_INSPECTION = {
  id: 'demo-tx',
  propertyAddress: '4210 Magnolia Creek Lane, Houston, TX 77095',
  clientName: 'David & Karen Nguyen',
  clientEmail: 'nguyen@email.com',
  inspectionDate: '2025-04-18',
}

const TX_ROOMS = [
  {
    id: 'tx-r1', name: 'I. Structural Systems', orderIndex: 0,
    narrative: 'The structural systems were inspected per TREC Standards of Practice. The slab-on-grade foundation is performing as designed with no significant deflection or displacement observed. Minor cosmetic hairline cracks were noted on the east and south exterior walls — these are consistent with normal curing shrinkage and seasonal expansion in the Houston clay-soil environment and do not indicate structural distress at this time. Grading on the west side of the property has settled and now directs surface water toward the foundation. This should be corrected by adding fill material to restore positive drainage away from the structure. Roof covering is composition shingle in satisfactory condition with an estimated 8–10 years of remaining service life.',
    items: [
      { id: 'tx-i1', name: 'A. Foundations', condition: 'good', notes: 'Slab-on-grade foundation performing as designed. No significant deflection or displacement. Minor cosmetic hairline cracks consistent with normal curing shrinkage in clay-soil conditions.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'tx-i2', name: 'B. Grading and Drainage', condition: 'fair', notes: 'West-side grading has settled — surface water directed toward foundation. Add fill material to restore positive drainage slope away from structure.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'tx-i3', name: 'C. Roof Covering Materials', condition: 'good', notes: 'Composition shingle roof in satisfactory condition. Estimated 8–10 years remaining service life. No active leaks or damaged shingles observed.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'tx-i4', name: 'E. Walls (Interior and Exterior)', condition: 'good', notes: 'Hairline cracks on east and south exterior walls — cosmetic, consistent with seasonal expansion. No structural concern at this time.', aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
  {
    id: 'tx-r2', name: 'II. Electrical Systems', orderIndex: 1,
    narrative: 'The electrical system is served by a 200-amp service panel located in the garage. The panel is in satisfactory condition with proper labeling and no evidence of double-tapped breakers, scorching, or improper wiring. GFCI protection was tested and confirmed functional at kitchen, bathroom, garage, and exterior outlets. One deficiency was identified: the exterior weatherproof-in-use cover on the south patio outlet is damaged and does not fully seal when a cord is plugged in — this cover should be replaced to maintain weather protection per NEC requirements.',
    items: [
      { id: 'tx-i5', name: 'A. Service Entrance and Panels', condition: 'good', notes: '200-amp panel in garage. Properly labeled, no double-tapping or scorching. Grounding and bonding intact.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'tx-i6', name: 'B. Branch Circuits, Connected Devices, and Fixtures', condition: 'fair', notes: 'All GFCI outlets tested functional. South patio exterior outlet weatherproof-in-use cover is damaged — replace to maintain NEC-compliant weather protection.', aiNarrative: null, photos: '[]', orderIndex: 1 },
    ],
  },
  {
    id: 'tx-r3', name: 'III. Heating, Ventilation, and Air Conditioning Systems', orderIndex: 2,
    narrative: 'The HVAC system consists of a gas furnace (Trane, 2020) and a central split-system air conditioner (Trane, 2020). Both units are operating within normal parameters. The measured temperature differential across the evaporator coil was 18°F, within the acceptable 15–22°F range. Ductwork is flexible insulated ducting routed through the attic — all accessible connections are intact with no visible damage or disconnections. The condensate drain line was flowing freely at the time of inspection. The air filter is a standard 1-inch pleated filter and was found to be moderately dirty — replacement is recommended and a 30-day replacement schedule should be maintained given the high-humidity Houston environment.',
    items: [
      { id: 'tx-i7', name: 'A. Heating Equipment', condition: 'good', notes: 'Gas furnace (Trane, 2020) operating normally. Heat exchanger shows no visible defects.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'tx-i8', name: 'B. Cooling Equipment', condition: 'good', notes: 'Central A/C (Trane, 2020) cooling to 18°F differential — within acceptable 15–22°F range. Condensate drain flowing freely.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'tx-i9', name: 'C. Duct Systems, Chases, and Vents', condition: 'good', notes: 'Flex duct in attic — all accessible connections intact. No visible damage or disconnections.', aiNarrative: null, photos: '[]', orderIndex: 2 },
      { id: 'tx-i10', name: 'D. Other', condition: 'fair', notes: 'Air filter moderately dirty. Replace immediately and maintain 30-day replacement schedule for Houston humidity conditions.', aiNarrative: null, photos: '[]', orderIndex: 3 },
    ],
  },
  {
    id: 'tx-r4', name: 'IV. Plumbing Systems', orderIndex: 3,
    narrative: 'The plumbing system is in satisfactory overall condition. Water supply is municipal with PEX distribution throughout the home. Water pressure was measured at 62 PSI, within the normal 40–80 PSI range. The gas water heater (A.O. Smith, 2021) is operating properly with the temperature-pressure relief valve present and discharge pipe terminating within 6 inches of the floor as required. A slow leak was observed at the supply valve connection beneath the master bathroom sink — the compression fitting should be tightened or replaced to prevent ongoing moisture damage to the vanity cabinet base.',
    items: [
      { id: 'tx-i11', name: 'A. Plumbing Supply, Distribution Systems and Fixtures', condition: 'fair', notes: 'PEX supply throughout. 62 PSI — normal range. Slow leak at master bath sink supply valve compression fitting — tighten or replace to prevent cabinet damage.', aiNarrative: null, photos: '[]', orderIndex: 0 },
      { id: 'tx-i12', name: 'B. Drains, Wastes, and Vents', condition: 'good', notes: 'All drains tested and flowing freely. No evidence of blockage or improper venting.', aiNarrative: null, photos: '[]', orderIndex: 1 },
      { id: 'tx-i13', name: 'C. Water Heating Equipment', condition: 'good', notes: 'Gas water heater (A.O. Smith, 2021) operating normally. TPR valve present, discharge pipe terminates within 6 inches of floor.', aiNarrative: null, photos: '[]', orderIndex: 2 },
    ],
  },
]

// ─── Page component (inner, reads search params) ────────────────────────────

function SampleReportInner() {
  const searchParams = useSearchParams()
  const urlState = searchParams.get('state')

  const [selectedFormat, setSelectedFormat] = useState<'TX' | 'OTHER'>(
    urlState?.toUpperCase() === 'TX' ? 'TX' : 'OTHER'
  )
  const [downloading, setDownloading] = useState(false)

  // Pick sample data based on selected format
  const { profile, inspection, rooms, filename } = useMemo(() => {
    if (selectedFormat === 'TX') {
      return {
        profile: TX_PROFILE,
        inspection: TX_INSPECTION,
        rooms: TX_ROOMS,
        filename: 'InspectIQ_TREC_Sample_Report.pdf',
      }
    }
    return {
      profile: OH_PROFILE,
      inspection: OH_INSPECTION,
      rooms: OH_ROOMS,
      filename: 'InspectIQ_Sample_Report.pdf',
    }
  }, [selectedFormat])

  async function downloadSample() {
    setDownloading(true)
    try {
      const blob = await pdf(
        <PDFReport
          inspection={inspection as never}
          rooms={rooms as never}
          profile={profile as never}
        />
      ).toBlob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      a.click()
      URL.revokeObjectURL(url)
    } finally {
      setDownloading(false)
    }
  }

  const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.useinspectiq.com' },
      { '@type': 'ListItem', position: 2, name: 'Sample Report', item: 'https://www.useinspectiq.com/sample-report' },
    ],
  }

  return (
    <div className="min-h-screen bg-white">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />

      <PublicNav activePath="/sample-report" />

      {/* ── Hero banner ── */}
      <div className="bg-slate-900 text-white">
        <div className="max-w-6xl mx-auto px-6 py-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 bg-blue-600/20 border border-blue-500/30 rounded-full px-3 py-1 text-blue-300 text-xs font-medium mb-4">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-400 inline-block" />
              Real Report · Fictional Client
            </div>
            <h1 className="text-2xl md:text-3xl font-bold mb-2">Sample Inspection Report</h1>
            <p className="text-slate-400 text-sm max-w-xl">
              This is an actual report generated by InspectIQ — the same output your clients receive. Fictional property and client, real software.
            </p>

            {/* ── State / format selector ── */}
            <div className="mt-4">
              <label htmlFor="format-select" className="text-xs text-slate-500 block mb-1">
                Your state
              </label>
              <select
                id="format-select"
                value={selectedFormat}
                onChange={(e) => setSelectedFormat(e.target.value as 'TX' | 'OTHER')}
                className="bg-slate-800 border border-slate-600 text-white text-sm rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="OTHER">Other States (InterNACHI)</option>
                <option value="TX">Texas (TREC 7-6)</option>
              </select>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 shrink-0">
            <Button
              onClick={downloadSample}
              disabled={downloading}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {downloading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Download className="h-4 w-4 mr-2" />}
              Download PDF
            </Button>
            <Link href="/auth/signup">
              <Button className="bg-blue-600 hover:bg-blue-700 w-full sm:w-auto">
                Start Free Trial
                <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </Link>
          </div>
        </div>
      </div>

      {/* ── Report viewer (desktop) / download prompt (mobile) ── */}
      <div className="max-w-6xl mx-auto px-6 py-10">
        {/* Desktop: live PDF viewer */}
        <div className="hidden md:block rounded-2xl overflow-hidden border border-slate-200 shadow-lg" style={{ height: '900px' }}>
          <PDFViewer width="100%" height="100%" showToolbar={false}>
            <PDFReport
              inspection={inspection as never}
              rooms={rooms as never}
              profile={profile as never}
            />
          </PDFViewer>
        </div>

        {/* Mobile: download prompt + report highlights */}
        <div className="md:hidden">
          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 text-center">
            <div className="w-14 h-14 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <Download className="h-6 w-6 text-blue-600" />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-2">Download the full report</h3>
            <p className="text-sm text-slate-500 mb-5 max-w-xs mx-auto">
              PDF reports look best downloaded. Tap below to save it and view the full {rooms.length}-section report on your device.
            </p>
            <Button onClick={downloadSample} disabled={downloading} className="bg-blue-600 hover:bg-blue-700 w-full max-w-xs">
              {downloading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Download className="h-4 w-4 mr-2" />}
              Download Sample PDF
            </Button>

            {/* Report preview highlights */}
            <div className="mt-6 text-left space-y-3">
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">What&apos;s in this report</p>
              {rooms.slice(0, 4).map((room) => (
                <div key={room.id} className="bg-white rounded-lg border border-slate-100 p-3">
                  <p className="text-sm font-medium text-slate-900">{room.name}</p>
                  <p className="text-xs text-slate-400 mt-0.5">{room.items.length} items inspected</p>
                  {room.items.filter((i: { condition: string }) => i.condition === 'poor').length > 0 && (
                    <span className="inline-block text-[10px] font-semibold px-1.5 py-0.5 rounded bg-red-100 text-red-700 mt-1">
                      {room.items.filter((i: { condition: string }) => i.condition === 'poor').length} critical
                    </span>
                  )}
                </div>
              ))}
              {rooms.length > 4 && (
                <p className="text-xs text-slate-400 text-center">+ {rooms.length - 4} more sections in the full report</p>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* ── What you just saw ── */}
      <div className="max-w-6xl mx-auto px-6 pb-16">
        <div className="bg-blue-50 border border-blue-100 rounded-2xl p-8 md:p-12">
          <div className="max-w-2xl mx-auto text-center">
            <h2 className="text-2xl font-bold text-slate-900 mb-3">This is what your clients receive</h2>
            <p className="text-slate-500 mb-8">
              Every report includes a professional cover page, summary of findings, room-by-room detail with condition ratings, and AI-generated narratives — finished in minutes, not hours.
            </p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
              {[
                { label: 'Cover Page', detail: 'With your logo & license' },
                { label: 'Findings Summary', detail: 'Critical items first' },
                { label: 'Room-by-Room', detail: 'AI narratives included' },
                { label: 'PDF + Share Link', detail: 'Email to client instantly' },
              ].map((item) => (
                <div key={item.label} className="bg-white rounded-xl p-4 border border-blue-100 text-center">
                  <CheckCircle2 className="h-5 w-5 text-blue-600 mx-auto mb-2" />
                  <p className="text-sm font-semibold text-slate-900">{item.label}</p>
                  <p className="text-xs text-slate-400 mt-1">{item.detail}</p>
                </div>
              ))}
            </div>
            <Link href="/auth/signup">
              <Button size="lg" className="bg-blue-600 hover:bg-blue-700 px-8">
                Start Your 14-Day Free Trial
                <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </Link>
            <p className="text-xs text-slate-400 mt-3">No credit card required · Cancel anytime · $99/month after trial</p>
            <p className="text-xs text-amber-600 font-medium mt-2">Founding member pricing ($99/mo locked forever) — only 50 spots available.</p>
          </div>
        </div>
      </div>

    </div>
  )
}

// ─── Wrapper with Suspense boundary (required by useSearchParams) ───────────

export default function SampleReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-white flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
      </div>
    }>
      <SampleReportInner />
    </Suspense>
  )
}
